Repository danielptv/bookmark-bar-switcher, pull requests merged in 2023-11, with the labels that each got.

#145 fix: Usage of wrong root folder in Opera
  .gitignore
  src/background/util.ts
Labels: bug

#155 docs: Document service worker code
  .eslintrc.yaml
  package-lock.json
  package.json
  src/background/handlers.ts
  src/background/service.ts
  src/background/storage.ts
  src/background/util.ts
Labels: documentation, enhancement

#159 ci: Set user to github-actions when bumping version
  .github/workflows/bump-release-publish.yaml
Labels: github_actions

#161 ci: Add issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  .markdownlintignore
  changelog.json
Labels: enhancement

#151 feat: Opera workspace sync
  .github/workflows/bump-release-publish.yaml
  .github/workflows/check-code-format.yaml
  .github/workflows/test.yaml
  README.md
  package-lock.json
  package.json
  src/background/handlers.ts
  src/background/main.ts
  src/background/service.ts
  src/background/storage.ts
  src/background/util.ts
  src/background/workspace.ts
  src/components/Add.vue
  src/components/BookmarkBars.vue
  src/components/Extension.vue
  src/popup/main.ts
  src/styles/global.scss
Labels: enhancement

#162 feat: Type-safe storage access
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  .markdownlintignore
  package-lock.json
  package.json
  src/background/storage.ts
Labels: enhancement

#163 docs: Add badges to README
  README.md
Labels: documentation

#172 feat: Remove unique bar names constraint
  .eslintrc.yaml
  .vscode/settings.json
  package-lock.json
  package.json
  src/background/handlers.ts
  src/background/main.ts
  src/background/service.ts
  src/background/storage.ts
  src/background/types.ts
  src/background/util.ts
  src/background/workspace.ts
  src/components/Add.vue
  src/components/Bar.vue
  src/components/BookmarkBars.vue
  src/components/Create.vue
  src/components/Edit.vue
  src/components/Extension.vue
  src/components/Modal.vue
  src/env.d.ts
  tsconfig.json
Labels: enhancement

#173 style: Fix all files previously ignored by ESLint
  .eslintignore
  jest.config.ts
  src/manifest.ts
  vite.config.ts
Labels: enhancement

#174 test: Use Vitest for testing
  .eslintrc.yaml
  __tests__/helpers.ts
  __tests__/popup.test.ts
  jest.config.ts
  package-lock.json
  package.json
  src/background/handlers.ts
  src/background/main.ts
  src/background/service.ts
  src/background/storage.ts
  src/background/util.ts
  src/components/BookmarkBars.vue
  src/components/Create.vue
  src/components/Edit.vue
  src/components/Modal.vue
  src/env.d.ts
  src/manifest.ts
  src/popup/App.vue
  src/popup/index.html
  src/styles/global.scss
  tsconfig.build.json
  tsconfig.json
  vite.config.ts
  vitest.config.ts
Labels: enhancement

#175 chore(deps): Migration to Vite 5 and Vitest 1.0
  package-lock.json
  package.json
  vite.config.ts
Labels: dependencies, javascript

#176 test: Include Opera browser in automated tests
  .github/workflows/bump-release-publish.yaml
  .github/workflows/test.yaml
  .vscode/extensions.json
  README.md
  __tests__/popup.test.ts
Labels: enhancement, github_actions
